### ISSUE TITLE
Error: Unrecognized command

### ISSUE THREAD

**Issue by roger-** [zigbeer/cc-znp#12]
I'm getting this error from something on my ZigBee network:

```
  cc-znp Error: Unrecognized command
  cc-znp     at new ZpiObject (/opt/zigbee2mqtt/node_modules/cc-znp/lib/zpiObject.js:37:15)
  cc-znp     at CcZnp._parseMtIncomingData (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:325:18)
  cc-znp     at Unpi.parseMtIncomingData (/opt/zigbee2mqtt/node_modules/cc-znp/lib/ccznp.js:92:18)
```

where subsys = ZDO  and cmd = 200 (decimal).

Any idea what this command is?

**Comment by joonas-fi** [comment]
I am researching the exact same thing. I don't have an idea, but my hunch is something related to "re-join" mechanics, as my network got pretty seriously borked and only after that I started receiving these messages.
